linters:
  flake8:
  eslint:
    config: "./eslint.config"
    fixer: true
  csslint:
    config: 'stylelint.config.js'
files:
  ignore:
    - "src/generated/*"
    - "webroot/bower_components/*"
    - "css"
    - "dist"
    - "index.html"
    - "src"
